
version: '3'
services:
  db:
    image: postgres:15
    volumes:
      - ./postgresql-data/:/var/lib/postgresql/data/:rw
    ports:
      - 6007:5432
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_user
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data
    networks:
      - network_2

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      CONSOLE_ACCESS_KEY: test
      CONSOLE_SECRET_KEY: test
    # command: server /data
    command: server --address ":9000" --console-address ":9001" /data

volumes:
  minio_data:

networks:
  network_2: